version: '2'
services: 
  db:
    image: mongo:latest
    ports: 
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foxxy
      - MONGO_INITDB_ROOT_PASSWORD=foxxy
      - MONGO_INITDB_ROOT_DATABASE=foxxy
  web:
    depends_on:
      - db
    build: .
    ports:
      - '8080:8080'
    environment:
      - FOXXY_DB_PORT=5432
      - FOXXY_DB_ADDR="127.0.0.1"
      - FOXXY_DB_NAME=foxxy
      - FOXXY_DB_USER=foxxy
      - FOXXY_DB_USER_PASSWORD=foxxy
    volumes:
      - ./dist:/app/dist